import type { Metadata } from 'next';
import '@/styles/globals.css';
import { Header } from '@/components/Header';

import { Layout } from '@/components/Layout';
import { MainNav } from '@/components/MainNav';
import { mainNavConfig } from '@/config';
import { Footer } from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-primary text-gray-100">
        <Header>
          <MainNav items={mainNavConfig.mainNav} />
        </Header>

        <Layout>
          <div className="py-20">{children} </div>
        </Layout>

        <Footer items={mainNavConfig.mainNav} />
      </body>
    </html>
  );
}
